# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py27

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_dev.txt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get remove -q -y gdal-bin libproj-dev libgeos-c1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable

  # Required to install Pillow
  - sudo apt-get -q -y install build-essential
  # GIS requirements.
  - sudo apt-get -q -y install binutils gdal-bin libproj-dev libgeos-c1 libnetcdf-dev libgdal1h-dev libgdal1h

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: SiggyF
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: openearth/flowmap
    condition: $TOXENV == py27
